#!/usr/bin/env python3
"""viz-dither — hard-edged 1-bit pixel icon set (self-authored, secure).

12x12 bitmaps in the same 1-bit family as the dither imagery, so icons and
graphics read as one system. Single source of truth here; emits:
  1. a contact-sheet PNG for isolated legibility review, and
  2. <out>/pixel-icons.js  ([x,y] filled-cell data for a <PixelIcon> component).

Icons render with currentColor, so they tint to any palette value in CSS.
Add your own glyphs by appending '#'/'.' grids to ICONS.

Usage: python3 pixel_icons.py --out ./icons
"""
import argparse, json, os
from PIL import Image

# 12x12 grids. '#' = filled cell, '.' = empty. Fit each glyph to ~10 cells so
# they share an optical box.
ICONS = {
    "stack": ["............", "...######...", "..#......#..", "...######...",
              "............", "...######...", "..#......#..", "...######...",
              "............", "...######...", "..#......#..", "...######..."],
    "mail": ["............", "..########..", "..#......#..", "..##....##..",
             "..#.#..#.#..", "..#..##..#..", "..#......#..", "..#......#..",
             "..#......#..", "..########..", "............", "............"],
    "page": ["............", "..#######...", "..#.....#...", "..#.###.#...",
             "..#.....#...", "..#.###.#...", "..#.....#...", "..#.###.#...",
             "..#.....#...", "..#######...", "............", "............"],
    "database": ["...#####....", "..#######...", "..#.....#...", "..#.....#...",
                 "..#######...", "..#.....#...", "..#.....#...", "..#######...",
                 "..#.....#...", "..#######...", "...#####....", "............"],
    "bot": ["....#..#....", "....#..#....", "..########..", ".#........#.",
            ".#.##..##.#.", ".#........#.", ".#........#.", ".#.######.#.",
            ".#........#.", "..########..", "...#....#...", "............"],
    "check": ["............", "..........#.", ".........##.", "........##..",
              ".#.....##...", ".##...##....", "..##.##.....", "...###......",
              "....#.......", "............", "............", "............"],
    "arrow": ["............", "............", "......#.....", "......##....",
              ".#######....", ".########...", ".#######....", "......##....",
              "......#.....", "............", "............", "............"],
    "spark": ["............", ".....##.....", ".....##.....", ".#...##...#.",
              "..#..##..#..", "...######...", "...######...", "..#..##..#..",
              ".#...##...#.", ".....##.....", ".....##.....", "............"],
    "bolt": ["............", "......###...", ".....###....", "....###.....",
             "...######...", "....####....", "...###......", "..###.......",
             ".###........", "............", "............", "............"],
    "target": ["............", "...######...", "..#......#..", ".#..####..#.",
               ".#.#....#.#.", ".#.#.##.#.#.", ".#.#.##.#.#.", ".#.#....#.#.",
               ".#..####..#.", "..#......#..", "...######...", "............"],
}


def render_contact(out):
    cell, gap, cols = 8, 24, 5
    icon_px = 12 * cell
    names = list(ICONS.keys())
    rows = (len(names) + cols - 1) // cols
    W = cols * (icon_px + gap) + gap
    H = rows * (icon_px + gap) + gap
    sheet = Image.new("RGB", (W, H), (250, 249, 247))
    px = sheet.load()
    for i, name in enumerate(names):
        r, c = divmod(i, cols)
        ox, oy = gap + c * (icon_px + gap), gap + r * (icon_px + gap)
        for y, line in enumerate(ICONS[name]):
            for x, ch in enumerate(line):
                if ch == "#":
                    for dy in range(cell):
                        for dx in range(cell):
                            px[ox + x * cell + dx, oy + y * cell + dy] = (15, 15, 15)
    sheet.save(f"{out}/_icons-contact.png")
    print("wrote contact sheet")


def emit_js(out):
    data = {name: [[x, y] for y, line in enumerate(g) for x, ch in enumerate(line) if ch == "#"]
            for name, g in ICONS.items()}
    with open(f"{out}/pixel-icons.js", "w") as f:
        f.write("// AUTO-GENERATED by viz-dither/scripts/pixel_icons.py — do not hand-edit.\n")
        f.write("export const PIXEL_GRID = 12;\n")
        f.write("export const PIXEL_ICONS = " + json.dumps(data, separators=(",", ":")) + ";\n")
    print("wrote pixel-icons.js", len(data), "icons")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="./icons")
    a = ap.parse_args()
    os.makedirs(a.out, exist_ok=True)
    render_contact(a.out)
    emit_js(a.out)
