#!/usr/bin/env python3
"""Build AI-OS daily notes: the human journal plus an auto session index plus
the day's Notion saves.

The daily note at ``daily/<YYYY-MM-DD>.md`` is a third memory layer that sits
beside ``context/memory/`` (the machine session log) and ``context/MEMORY.md``
(the small scratchpad). It is the human-facing, backlinked surface you
collaborate in inside Obsidian.

This script owns ONLY the region between the ``aios:auto`` markers. Everything
above it (your Journal) is never touched. A past day's auto block is written
once and then left frozen, so the note stays a permanent record of that day.
Pass ``--force`` to rebuild a frozen day.

Data sources, all already maintained by AI-OS:
  - Sessions:     context/memory/<date>.md    (session blocks with titles + ids)
  - Notion saves: context/notion/items/<db>/*.md  (nightly sync of Resources,
                  Stack, and Notes)

Usage:
  python3 scripts/daily-note.py [YYYY-MM-DD] [--force]
  python3 scripts/daily-note.py --catch-up        # finalize yesterday, refresh today
  python3 scripts/daily-note.py --backfill         # build every past day with data
"""

import re
import sys
from datetime import date as date_cls, datetime, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DAILY = ROOT / "daily"
MEM = ROOT / "context" / "memory"
NOTION_ITEMS = ROOT / "context" / "notion" / "items"

AUTO_START = (
    "<!-- aios:auto:start - generated by scripts/daily-note.sh; "
    "edits between these markers are overwritten -->"
)
AUTO_END = "<!-- aios:auto:end -->"

# Notion databases we surface in the daily note, in display order, keyed by the
# items/<key> folder the sync writes to.
#   desc: include the item's one-line description (safe for public tool/resource
#         listings; OFF for Notes, whose bodies are personal and may hold anything).
#   link: "url" uses the item's external URL; "notion" links to the Notion page.
NOTION_DBS = [
    {"key": "resources", "label": "Resources", "desc": True, "link": "url"},
    {"key": "stack", "label": "Apps & tools (Stack)", "desc": True, "link": "url"},
    # Notes hold personal/client material: title + Notion link only, never the
    # body, so nothing sensitive typed into a note can reach the daily page.
    {"key": "notes", "label": "Notes", "desc": False, "link": "notion"},
]


def read_frontmatter(text):
    """Small YAML-ish frontmatter reader: scalars and simple [a, b] / dash lists."""
    fm = {}
    if not text.startswith("---"):
        return fm
    end = text.find("\n---", 3)
    if end == -1:
        return fm
    key = None
    for line in text[3:end].splitlines():
        if not line.strip():
            continue
        m = re.match(r"^([A-Za-z0-9_]+):\s*(.*)$", line)
        if m:
            key, val = m.group(1), m.group(2).strip()
            if val.startswith("[") and val.endswith("]"):
                fm[key] = [x.strip().strip("\"'") for x in val[1:-1].split(",") if x.strip()]
            elif val == "":
                fm[key] = []
            else:
                fm[key] = val.strip("\"'")
        else:
            m2 = re.match(r"^\s*-\s+(.*)$", line)
            if m2 and isinstance(fm.get(key), list):
                fm[key].append(m2.group(1).strip().strip("\"'"))
    return fm


def load_clients():
    """Discover client slugs and aliases from clients/<slug>/<slug>.md frontmatter.

    Returns an ``alias_lower -> slug`` map. Discovered dynamically so it scales
    to any number of clients and never hardcodes a list.
    """
    alias_to_slug = {}
    clients_dir = ROOT / "clients"
    if not clients_dir.is_dir():
        return alias_to_slug
    for d in sorted(clients_dir.iterdir()):
        if not d.is_dir():
            continue
        slug = d.name
        alias_to_slug[slug.lower()] = slug
        hub = d / f"{slug}.md"
        if hub.exists():
            fm = read_frontmatter(hub.read_text(encoding="utf-8", errors="ignore"))
            for a in fm.get("aliases", []) or []:
                a = a.strip().lower()
                if a:
                    alias_to_slug[a] = slug
    return alias_to_slug


def detect_clients(block_text, alias_to_slug):
    """Return sorted client slugs mentioned in a block, matched as whole words."""
    found = set()
    low = block_text.lower()
    for alias, slug in alias_to_slug.items():
        if re.search(r"(?<![a-z0-9])" + re.escape(alias) + r"(?![a-z0-9])", low):
            found.add(slug)
    return sorted(found)


def parse_sessions(date_str):
    """Return [(n, title, body)] for each ## Session N block in the day's log."""
    f = MEM / f"{date_str}.md"
    if not f.exists():
        return []
    text = f.read_text(encoding="utf-8", errors="ignore")
    parts = re.split(r"(?m)^##\s+Session\s+(\d+)\s*$", text)
    sessions = []
    for i in range(1, len(parts), 2):
        n = parts[i]
        body = parts[i + 1] if i + 1 < len(parts) else ""
        tm = re.search(r"(?m)^###\s+Title\s*\n(.+)$", body)
        title = tm.group(1).strip() if tm else ""
        sessions.append((n, title, body))
    return sessions


def truncate(s, n):
    s = " ".join((s or "").split())
    return s if len(s) <= n else s[: n - 1].rstrip() + "..."


def extract_desc(text):
    """First line of the ## Description section, or first real body line."""
    m = re.search(r"(?ms)^##\s+Description\s*\n(.+?)(?:\n##\s|\Z)", text)
    if m:
        first = m.group(1).strip().splitlines()
        if first:
            return first[0].strip()
    body = re.sub(r"(?s)^---.*?\n---\n", "", text)
    for line in body.splitlines():
        t = line.strip()
        if t and not t.startswith("#") and not t.lower().startswith("tags:"):
            return t
    return ""


def notion_url(notion_id):
    """Build a clickable Notion page URL from a page id (with or without dashes)."""
    nid = (notion_id or "").replace("-", "")
    return f"https://www.notion.so/{nid}" if nid else ""


def scan_notion_index():
    """One pass over context/notion/items/. Returns {date: {key: [bullet, ...]}}.

    Pre-rendering every Notion save once and bucketing by date makes a full
    backfill O(items) instead of O(items x days). Note bodies are never emitted
    (desc is off for the notes database), only title + Notion link.
    """
    index = {}
    for db in NOTION_DBS:
        key = db["key"]
        folder = NOTION_ITEMS / key
        if not folder.is_dir():
            continue
        for f in sorted(folder.glob("*.md")):
            text = f.read_text(encoding="utf-8", errors="ignore")
            fm = read_frontmatter(text)
            d = fm.get("date")
            if not d or not re.match(r"^\d{4}-\d{2}-\d{2}$", str(d)):
                continue
            name = truncate(fm.get("name", f.stem), 90)
            rel = f"context/notion/items/{key}/{f.stem}"
            line = f"- [[{rel}|{name}]]"
            if db["desc"]:
                desc = extract_desc(text)
                if desc:
                    line += f": {truncate(desc, 160)}"
            link = fm.get("url", "") if db["link"] == "url" else notion_url(fm.get("notion_id", ""))
            if link:
                line += f" ([link]({link}))"
            index.setdefault(d, {}).setdefault(key, []).append(line)
    return index


def build_sessions_section(date_str, alias_to_slug):
    sessions = parse_sessions(date_str)
    lines = ["## Sessions"]
    if not sessions:
        lines.append("_No AI-OS sessions logged yet._")
        return "\n".join(lines)
    for n, title, body in sessions:
        label = f"Session {n}: {title}" if title else f"Session {n}"
        link = f"[[context/memory/{date_str}#Session {n}|{label}]]"
        clients = detect_clients(body, alias_to_slug)
        suffix = ""
        if clients:
            suffix = " (clients: " + " ".join(f"[[{c}]]" for c in clients) + ")"
        lines.append(f"- {link}{suffix}")
    return "\n".join(lines)


def build_notion_section(date_str, notion_index):
    lines = ["## Saved to Notion today"]
    per_key = notion_index.get(date_str, {})
    any_items = False
    for db in NOTION_DBS:
        items = sorted(per_key.get(db["key"], []))
        if items:
            any_items = True
            lines.append(f"### {db['label']}")
            lines.extend(items)
    if not any_items:
        lines.append("_Nothing saved to Notion today._")
    return "\n".join(lines)


def build(date_str, alias_to_slug, notion_index, force=False):
    today = date_cls.today().isoformat()
    DAILY.mkdir(exist_ok=True)
    note = DAILY / f"{date_str}.md"
    auto_body = "\n\n".join(
        [
            build_sessions_section(date_str, alias_to_slug),
            build_notion_section(date_str, notion_index),
        ]
    )
    auto_block = f"{AUTO_START}\n{auto_body}\n{AUTO_END}"

    if note.exists():
        existing = note.read_text(encoding="utf-8", errors="ignore")
        has_block = AUTO_END in existing
        if date_str < today and has_block and not force:
            return "frozen"
        if has_block:
            new = re.sub(
                re.escape(AUTO_START) + r".*?" + re.escape(AUTO_END),
                lambda _m: auto_block,
                existing,
                flags=re.S,
            )
        else:
            new = existing.rstrip() + "\n\n" + auto_block + "\n"
        if new != existing:
            note.write_text(new, encoding="utf-8")
            return "updated"
        return "unchanged"
    skeleton = (
        f"---\ndate: {date_str}\ntype: daily\ntags: [daily]\n---\n"
        f"# {date_str}\n\n"
        f"## Journal\n\n\n"
        f"{auto_block}\n"
    )
    note.write_text(skeleton, encoding="utf-8")
    return "created"


def all_dates(notion_index):
    """Every date with a session log or a Notion save, sorted."""
    dates = set(notion_index.keys())
    if MEM.is_dir():
        for f in MEM.glob("*.md"):
            m = re.match(r"^(\d{4}-\d{2}-\d{2})\.md$", f.name)
            if m:
                dates.add(m.group(1))
    return sorted(dates)


def main():
    args = sys.argv[1:]
    force = "--force" in args
    alias_to_slug = load_clients()
    notion_index = scan_notion_index()

    if "--backfill" in args:
        dates = all_dates(notion_index)
        counts = {}
        for d in dates:
            r = build(d, alias_to_slug, notion_index, force=False)
            counts[r] = counts.get(r, 0) + 1
        summary = ", ".join(f"{k}: {v}" for k, v in sorted(counts.items()))
        print(f"backfill: {len(dates)} dates -> {summary}")
        return

    if "--catch-up" in args:
        yesterday = (date_cls.today() - timedelta(days=1)).isoformat()
        for d in (yesterday, date_cls.today().isoformat()):
            print(f"{build(d, alias_to_slug, notion_index, force=True)}: {DAILY / (d + '.md')}")
        return

    positional = [a for a in args if not a.startswith("--")]
    date_str = positional[0] if positional else date_cls.today().isoformat()
    try:
        datetime.strptime(date_str, "%Y-%m-%d")
    except ValueError:
        sys.exit(f"bad date: {date_str} (expected YYYY-MM-DD)")
    print(f"{build(date_str, alias_to_slug, notion_index, force=force)}: {DAILY / (date_str + '.md')}")


if __name__ == "__main__":
    main()
