#!/usr/bin/env python3
"""
gen-skills-catalog.py - generate docs/skills-catalog.md from the actual skill files.

Scans:
  .claude/skills/<name>/SKILL.md      -> LIVE skills, invocable with /<name>
  skills-library/backlog/<pack>/<name>/SKILL.md -> LIBRARY skills (review-only)

Run: python3 scripts/gen-skills-catalog.py
"""
import os, re, glob, datetime, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "skills-catalog.md"


def parse_frontmatter(path):
    name = ""
    desc = ""
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return name, desc
    m = re.search(r"^---\s*\n(.*?)\n---", text, re.S)
    block = m.group(1) if m else text[:1500]
    nm = re.search(r"^name:\s*(.+)$", block, re.M)
    if nm:
        name = nm.group(1).strip().strip("\"'")
    dm = re.search(r"^description:\s*(.+?)(?:\n[a-zA-Z_]+:|\Z)", block, re.S | re.M)
    if dm:
        desc = " ".join(dm.group(1).split()).strip().strip("\"'")
    return name, desc


def first_sentence(desc, limit=200):
    if not desc:
        return ""
    desc = desc.lstrip("> ").strip().replace("|", "/")
    # cut at first period followed by space, else hard limit
    cut = desc
    for sep in [". ", ".\n"]:
        i = desc.find(sep)
        if 0 < i < limit:
            cut = desc[: i + 1]
            break
    if len(cut) > limit:
        cut = cut[:limit].rsplit(" ", 1)[0] + "..."
    return cut


lines = []
lines.append("# AI-OS Skills Catalog")
lines.append("")
lines.append("*Auto-generated by `scripts/gen-skills-catalog.py`. Do not hand-edit; rerun the script.*")
lines.append("")
lines.append("Two tiers. LIVE skills are active and you invoke them by typing a forward slash plus the exact name (the slash name, the folder name, and the frontmatter name all match). LIBRARY skills are staging candidates in `skills-library/`; they are NOT invocable until promoted into `.claude/skills/`.")
lines.append("")

# --- LIVE ---
live_dir = ROOT / ".claude" / "skills"
live = []
for d in sorted(live_dir.iterdir()):
    if not d.is_dir() or d.name == "_catalog":
        continue
    sk = d / "SKILL.md"
    if not sk.exists():
        continue
    name, desc = parse_frontmatter(sk)
    invoke = name or d.name
    live.append((invoke, d.name, first_sentence(desc)))

lines.append(f"## Live skills ({len(live)}) - invoke with `/name`")
lines.append("")
lines.append("| Invoke | Folder | What it does |")
lines.append("|--------|--------|--------------|")
for invoke, folder, desc in live:
    flag = "" if invoke == folder else f" (frontmatter differs: `{invoke}`)"
    lines.append(f"| `/{invoke}` | `.claude/skills/{folder}/`{flag} | {desc} |")
lines.append("")

# --- LIBRARY ---
lib_backlog = ROOT / "skills-library" / "backlog"
lines.append("## Skills library (staging, review-only, not invocable)")
lines.append("")
lines.append("These live under `skills-library/backlog/<pack>/<name>/`. To make one live: move it through `triage/` then `review/`, rename to the `{category}-{name}` convention, and register it in `.claude/skills/` and `AGENTS.md`. See `skills-library/README.md`.")
lines.append("")

total_lib = 0
if lib_backlog.is_dir():
    for pack in sorted(lib_backlog.iterdir()):
        if not pack.is_dir():
            continue
        skills = sorted([s for s in pack.iterdir() if s.is_dir() and (s / "SKILL.md").exists()])
        if not skills:
            continue
        lines.append(f"### backlog/{pack.name} ({len(skills)})")
        lines.append("")
        lines.append("| Skill folder | What it does |")
        lines.append("|--------------|--------------|")
        for s in skills:
            name, desc = parse_frontmatter(s / "SKILL.md")
            lines.append(f"| `{pack.name}/{s.name}/` | {first_sentence(desc)} |")
            total_lib += 1
        lines.append("")

lines.append("---")
lines.append("")
lines.append(f"Totals: {len(live)} live skills, {total_lib} library skills.")
lines.append("")

text = "\n".join(lines)
text = text.replace("\u2014", "-").replace("\u2013", "-")  # no em/en dashes
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(text, encoding="utf-8")
print(f"wrote {OUT} ({len(live)} live, {total_lib} library)")
